const UNIVERSES = {
  marvel: {
    key: 'marvel',
    label: 'Marvel',
    title: 'Marvel Universe',
    tagline: 'Phases, legacy cartoons, live-action shows, and every multiverse branch in one place.',
    phaseLabel: 'Phase',
    accent: 'red',
    heroQuery: 'Marvel',
    timeline: [
      { key: 'legacy', label: 'Legacy & Origins', from: 1940, to: 2007, description: 'Pre-MCU films, animated runs, and early television experiments.' },
      { key: 'phase-1', label: 'Phase One', from: 2008, to: 2012, description: 'The first big-screen era that set the modern Marvel rhythm.' },
      { key: 'phase-2', label: 'Phase Two', from: 2013, to: 2015, description: 'Expanding the world with sequels, crossovers, and TV branches.' },
      { key: 'phase-3', label: 'Phase Three', from: 2016, to: 2019, description: 'The peak Infinity Saga stretch with movies and series alike.' },
      { key: 'multiverse', label: 'Multiverse Era', from: 2020, to: 2100, description: 'Streaming-era chapters, animated experiments, and multiverse stories.' },
    ],
    sources: [
      { key: 'marvel-core', label: 'Marvel Core', query: 'Marvel', pages: 2 },
      { key: 'marvel-studios', label: 'Marvel Studios', query: 'Marvel Studios', pages: 1 },
      { key: 'spider-man', label: 'Spider-Man', query: 'Spider-Man', pages: 1 },
      { key: 'x-men', label: 'X-Men', query: 'X-Men', pages: 1 },
      { key: 'fantastic-four', label: 'Fantastic Four', query: 'Fantastic Four', pages: 1 },
      { key: 'avengers', label: 'Avengers', query: 'Avengers', pages: 1 },
      { key: 'iron-man', label: 'Iron Man', query: 'Iron Man', pages: 1 },
      { key: 'captain-america', label: 'Captain America', query: 'Captain America', pages: 1 },
      { key: 'thor', label: 'Thor', query: 'Thor', pages: 1 },
      { key: 'deadpool', label: 'Deadpool', query: 'Deadpool', pages: 1 },
      { key: 'daredevil', label: 'Daredevil & Defenders', query: 'Daredevil', pages: 1 },
      { key: 'guardians', label: 'Guardians of the Galaxy', query: 'Guardians of the Galaxy', pages: 1 },
      { key: 'loki', label: 'Loki & What If', query: 'Loki', pages: 1 },
      { key: 'marvel-tv', label: 'Marvel TV', query: 'Agents of S.H.I.E.L.D.', pages: 1 },
      { key: 'animated-marvel', label: 'Animated Marvel', query: 'Spider-Man', pages: 1 },
    ],
  },
  dc: {
    key: 'dc',
    label: 'DC',
    title: 'DC Universe',
    tagline: 'Batman, Superman, animated classics, live-action series, and every elseworld worth exploring.',
    phaseLabel: 'Era',
    accent: 'blue',
    heroQuery: 'DC',
    timeline: [
      { key: 'legacy', label: 'Golden & Silver Age', from: 1940, to: 1988, description: 'Classic serials, super-friends, and the earliest screen legends.' },
      { key: 'modern', label: 'Modern Rebuild', from: 1989, to: 2004, description: 'The big-screen return of Batman, Superman, and the animated renaissance.' },
      { key: 'cinematic', label: 'Cinematic Rebuild', from: 2005, to: 2012, description: 'Dark Knight-era films and the TV/animation ecosystem starting to expand.' },
      { key: 'arrowverse', label: 'Arrowverse & TV Surge', from: 2013, to: 2019, description: 'DC television, shared-world series, and animated spin-offs.' },
      { key: 'new-age', label: 'New Age & Elseworlds', from: 2020, to: 2100, description: 'Fresh live-action, animated projects, and new chapter experiments.' },
    ],
    sources: [
      { key: 'dc-core', label: 'DC Core', query: 'DC Comics', pages: 2 },
      { key: 'batman', label: 'Batman', query: 'Batman', pages: 1 },
      { key: 'superman', label: 'Superman', query: 'Superman', pages: 1 },
      { key: 'wonder-woman', label: 'Wonder Woman', query: 'Wonder Woman', pages: 1 },
      { key: 'justice-league', label: 'Justice League', query: 'Justice League', pages: 1 },
      { key: 'teen-titans', label: 'Teen Titans', query: 'Teen Titans', pages: 1 },
      { key: 'young-justice', label: 'Young Justice', query: 'Young Justice', pages: 1 },
      { key: 'arrowverse', label: 'Arrowverse', query: 'Arrow', pages: 1 },
      { key: 'flash', label: 'The Flash', query: 'The Flash', pages: 1 },
      { key: 'harley-quinn', label: 'Harley Quinn', query: 'Harley Quinn', pages: 1 },
      { key: 'suicide-squad', label: 'Suicide Squad', query: 'Suicide Squad', pages: 1 },
      { key: 'super-friends', label: 'Super Friends', query: 'Super Friends', pages: 1 },
      { key: 'batman-animated', label: 'Batman Animated', query: 'Batman: The Animated Series', pages: 1 },
      { key: 'superman-animated', label: 'Superman Animated', query: 'Superman: The Animated Series', pages: 1 },
      { key: 'classic-tv', label: 'Classic DC TV', query: 'Lois & Clark', pages: 1 },
    ],
  },
}

module.exports = { UNIVERSES }
